#!/usr/bin/env ruby
# frozen_string_literal: true

# Backfill thumbnail generator for album/post/draft images.
#
# Scans assets/images/{posts,albums,drafts}/ for source images, generates
# <basename>-thumb.jpg (<=600w, q78) and <basename>-med.jpg (<=1600w, q82)
# next to each source, and writes a manifest to _data/image_meta.yml.
#
# Usage:
#   bundle exec ruby scripts/generate_thumbnails.rb [--force] [--only posts|albums|drafts] [--verbose]
#
# Idempotent: skips images whose thumbs already exist and are newer than source.
# Requires ImageMagick on PATH (brew install imagemagick).

require 'fileutils'
require 'optparse'
require 'yaml'
require 'pathname'

begin
  require 'mini_magick'
rescue LoadError
  abort "error: mini_magick gem not installed. Run `bundle install` first."
end

ROOT      = File.expand_path('..', __dir__)
IMAGE_DIR = File.join(ROOT, 'assets', 'images')
DATA_DIR  = File.join(ROOT, '_data')
MANIFEST  = File.join(DATA_DIR, 'image_meta.yml')

SUBDIRS   = %w[posts albums drafts].freeze
EXTS      = %w[.png .jpg .jpeg .PNG .JPG .JPEG].freeze

THUMB_W   = 600
MED_W     = 1600
THUMB_Q   = 78
MED_Q     = 82

options = { force: false, only: nil, verbose: false }
OptionParser.new do |opts|
  opts.banner = 'Usage: generate_thumbnails.rb [options]'
  opts.on('--force', 'Regenerate thumbnails even if up to date') { options[:force] = true }
  opts.on('--only SUBDIR', SUBDIRS, "Only process one of: #{SUBDIRS.join(', ')}") { |v| options[:only] = v }
  opts.on('--verbose', 'Log every processed file') { options[:verbose] = true }
  opts.on('-h', '--help', 'Show help') { puts opts; exit }
end.parse!

unless system('magick -version > /dev/null 2>&1') || system('convert -version > /dev/null 2>&1')
  abort "error: ImageMagick not found on PATH. Install with `brew install imagemagick`."
end

def variant_path(source_abs, variant)
  dir  = File.dirname(source_abs)
  base = File.basename(source_abs, File.extname(source_abs))
  File.join(dir, "#{base}-#{variant}.jpg")
end

def needs_regen?(source_abs, variant_abs, force)
  return true if force
  return true unless File.exist?(variant_abs)
  File.mtime(variant_abs) < File.mtime(source_abs)
end

def write_variant(source_abs, out_abs, max_w, quality, verbose:)
  img = MiniMagick::Image.open(source_abs)
  orig_w = img.width
  orig_h = img.height

  img.combine_options do |c|
    c.auto_orient
    if File.extname(source_abs).downcase == '.png'
      c.background 'white'
      c.alpha 'remove'
      c.alpha 'off'
    end
    c.strip
    c.resize "#{max_w}x>"
    c.interlace 'Plane'
    c.quality quality.to_s
  end
  img.format 'jpg'
  img.write(out_abs)

  out = MiniMagick::Image.open(out_abs)
  puts "  wrote #{File.basename(out_abs)} (#{out.width}x#{out.height}, #{format_bytes(File.size(out_abs))})" if verbose
  [out.width, out.height, orig_w, orig_h]
end

def format_bytes(n)
  return "#{n} B" if n < 1024
  return format('%.1f KB', n / 1024.0) if n < 1024 * 1024
  format('%.1f MB', n / (1024.0 * 1024.0))
end

def thumb_or_med_suffix?(name)
  name =~ /-(thumb|med)\.jpg\z/i
end

def iso_path(abs)
  Pathname.new(abs).relative_path_from(Pathname.new(IMAGE_DIR)).to_s
end

def load_existing_manifest(path)
  return {} unless File.exist?(path)
  data = YAML.safe_load(File.read(path), aliases: false) || {}
  data.is_a?(Hash) ? data : {}
rescue Psych::SyntaxError
  warn "warning: could not parse #{path}; starting fresh"
  {}
end

def sort_hash_deep(obj)
  case obj
  when Hash
    obj.keys.sort.each_with_object({}) { |k, acc| acc[k] = sort_hash_deep(obj[k]) }
  when Array
    obj.map { |x| sort_hash_deep(x) }
  else
    obj
  end
end

def write_manifest_atomically(path, data)
  FileUtils.mkdir_p(File.dirname(path))
  tmp = "#{path}.tmp"
  File.write(tmp, manifest_header + sort_hash_deep(data).to_yaml(line_width: -1))
  File.rename(tmp, path)
end

def manifest_header
  <<~HEADER
    # Generated by scripts/generate_thumbnails.rb. Do not edit by hand.
    # Each key is a path under assets/images/. `cf_id` (when set) is reserved
    # for Cloudflare Images integration and is preserved on regeneration.
  HEADER
end

manifest = load_existing_manifest(MANIFEST)
processed = 0
skipped = 0
errors = 0

subdirs = options[:only] ? [options[:only]] : SUBDIRS

subdirs.each do |sub|
  src_dir = File.join(IMAGE_DIR, sub)
  next unless Dir.exist?(src_dir)

  Dir.glob(File.join(src_dir, '*')).sort.each do |abs|
    next unless File.file?(abs)
    next unless EXTS.include?(File.extname(abs))
    next if thumb_or_med_suffix?(File.basename(abs))

    rel_key = iso_path(abs)
    thumb_abs = variant_path(abs, 'thumb')
    med_abs   = variant_path(abs, 'med')

    if !needs_regen?(abs, thumb_abs, options[:force]) && !needs_regen?(abs, med_abs, options[:force]) && manifest.key?(rel_key)
      skipped += 1
      puts "skip  #{rel_key}" if options[:verbose]
      next
    end

    puts "gen   #{rel_key}"

    begin
      thumb_w, thumb_h, orig_w, orig_h = write_variant(abs, thumb_abs, THUMB_W, THUMB_Q, verbose: options[:verbose])
      med_w,   med_h,   _,      _      = write_variant(abs, med_abs,   MED_W,   MED_Q,   verbose: options[:verbose])

      existing = manifest[rel_key] || {}
      entry = {
        'w' => orig_w,
        'h' => orig_h,
        'thumb' => { 'src' => iso_path(thumb_abs), 'w' => thumb_w, 'h' => thumb_h },
        'med'   => { 'src' => iso_path(med_abs),   'w' => med_w,   'h' => med_h }
      }
      entry['cf_id'] = existing['cf_id'] if existing.key?('cf_id')
      manifest[rel_key] = entry
      processed += 1
    rescue StandardError => e
      warn "error processing #{rel_key}: #{e.message}"
      errors += 1
    end
  end
end

manifest_keys_on_disk = manifest.keys.select { |k| File.exist?(File.join(IMAGE_DIR, k)) }
removed = manifest.keys - manifest_keys_on_disk
removed.each do |k|
  puts "prune #{k} (source missing)"
  manifest.delete(k)
end

write_manifest_atomically(MANIFEST, manifest)

puts '---'
puts "processed: #{processed}"
puts "skipped:   #{skipped}"
puts "pruned:    #{removed.size}"
puts "errors:    #{errors}"
puts "manifest:  #{Pathname.new(MANIFEST).relative_path_from(Pathname.new(ROOT))}  (#{manifest.size} entries)"
exit(errors.zero? ? 0 : 1)
