#!/usr/bin/env ruby
# frozen_string_literal: true

require 'optparse'
require 'yaml'
require 'aws-sdk-s3'
require 'net/http'

ROOT = File.expand_path('..', __dir__)
IMAGE_DIR = File.join(ROOT, 'assets', 'images')
MANIFEST_PATH = File.join(ROOT, '_data', 'image_meta.yml')

def env!(name)
  value = ENV[name].to_s.strip
  abort "error: set #{name}" if value.empty?
  value
end

def r2_endpoint
  explicit = ENV['CLOUDFLARE_R2_S3_ENDPOINT'].to_s.strip
  return explicit unless explicit.empty?
  account_id = env!('CLOUDFLARE_ACCOUNT_ID')
  "https://#{account_id}.r2.cloudflarestorage.com"
end

def public_base_url
  ENV['CLOUDFLARE_R2_PUBLIC_BASE_URL'].to_s.strip
end

def bucket
  env!('CLOUDFLARE_R2_BUCKET')
end

def s3_client
  @s3_client ||= Aws::S3::Client.new(
    region: 'auto',
    endpoint: r2_endpoint,
    access_key_id: env!('CLOUDFLARE_R2_ACCESS_KEY_ID'),
    secret_access_key: env!('CLOUDFLARE_R2_SECRET_ACCESS_KEY'),
    force_path_style: true
  )
end

def load_manifest
  data = YAML.safe_load(File.read(MANIFEST_PATH), aliases: false) || {}
  data.is_a?(Hash) ? data : {}
rescue Errno::ENOENT
  {}
end

def write_manifest(data)
  sorted = data.keys.sort.each_with_object({}) { |k, acc| acc[k] = data[k] }
  header = <<~HEADER
    # Generated by scripts/generate_thumbnails.rb. Do not edit by hand.
    # Each key is a path under assets/images/. `r2_key` (when set) is reserved
    # for Cloudflare R2 integration and is preserved on regeneration.
  HEADER
  tmp = "#{MANIFEST_PATH}.tmp"
  File.write(tmp, header + sorted.to_yaml(line_width: -1))
  File.rename(tmp, MANIFEST_PATH)
end

def object_exists?(key)
  s3_client.head_object(bucket: bucket, key: key)
  true
rescue Aws::S3::Errors::NotFound, Aws::S3::Errors::NoSuchKey
  false
end

def verify_delivery(key)
  return true if public_base_url.empty?
  uri = URI.parse("#{public_base_url.sub(%r{/$}, '')}/#{key}")
  resp = Net::HTTP.start(uri.host, uri.port, use_ssl: uri.scheme == 'https') do |http|
    http.request(Net::HTTP::Head.new(uri))
  end
  resp.code.to_i.between?(200, 399)
rescue StandardError
  false
end

def variant_keys(entry)
  return [] unless entry.is_a?(Hash)
  %w[thumb med].map do |variant|
    node = entry[variant]
    node.is_a?(Hash) ? node['src'].to_s.strip : ''
  end.reject(&:empty?)
end

options = { dry_run: false, verify: false, force: false }
OptionParser.new do |opts|
  opts.banner = 'Usage: sync_r2_images.rb [options]'
  opts.on('--dry-run', 'Print what would upload') { options[:dry_run] = true }
  opts.on('--verify', 'HEAD-check public URL after upload') { options[:verify] = true }
  opts.on('--force', 'Upload even if object already exists') { options[:force] = true }
  opts.on('-h', '--help', 'Show help') { puts opts; exit }
end.parse!

manifest = load_manifest
uploaded = 0
skipped = 0
missing = 0
verify_fail = 0

manifest.keys.sort.each do |key|
  next unless key.start_with?('posts/', 'albums/')
  entry = manifest[key]
  unless entry.is_a?(Hash)
    skipped += 1
    next
  end

  object_key = entry['r2_key'].to_s.strip
  object_key = key if object_key.empty?
  uploads = [[key, object_key]] + variant_keys(entry).map { |vk| [vk, vk] }

  if options[:dry_run]
    uploads.each { |src_rel, dest_key| puts "would upload #{src_rel} -> #{dest_key}" }
    next
  end

  uploads.each do |src_rel, dest_key|
    source_abs = File.join(IMAGE_DIR, src_rel)
    unless File.exist?(source_abs)
      warn "missing source for #{src_rel}"
      missing += 1
      next
    end

    if !options[:force] && object_exists?(dest_key)
      skipped += 1
      next
    end

    s3_client.put_object(bucket: bucket, key: dest_key, body: File.open(source_abs, 'rb'))
    uploaded += 1
    puts "uploaded #{src_rel} -> #{dest_key}"

    if options[:verify] && !verify_delivery(dest_key)
      verify_fail += 1
      warn "verify failed for #{dest_key}"
    end
  end

  entry['r2_key'] = object_key
  manifest[key] = entry
end

write_manifest(manifest) unless options[:dry_run]

puts '---'
puts "uploaded: #{uploaded}"
puts "skipped:  #{skipped}"
puts "missing:  #{missing}"
puts "verify_fail: #{verify_fail}" if options[:verify]
